### ISSUE TITLE
Instructions how to run in a browser? (serverless architecture)

### ISSUE THREAD

**Issue by marsrobertson** [kleros/archon#18]
I'm using serverless architecture.

I was thinking about using https://browserify.org/

1. `npm install -g browserify`
2. `yarn add @kleros/archon`
3. `browserify node_modules/@kleros/archon/lib/Archon.js -o bundle.js`

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Kleros Archon</title>

    <script src="bundle.js"></script>
    <script>
    	var archon = new Archon('https://mainnet.infura.io'); // Uncaught ReferenceError: Archon is not defined
    </script>
  </head>
  <body>
  
  </body>
</html>
```

Maybe there is a better way?

**Comment by marsrobertson** [comment]
Alternative, potential workaround - setup a super simple ([free tier](https://www.heroku.com/free)) Heroku app that will expose HTTP endpoints?

_(I'm a guy focusing on usability and user experience, managing and patching servers was never my cup of tea)_

**Comment by satello** [comment]
Browserify and other minifiers do not expose named variables unless you specifically ask them to. I prefer to use webpack to browserify as it tends to "just work" more for me than browserify. I just tested this out it is working.

1. `npm install -g webpack webpack-cli`
2. `yarn add @kleros/archon`
3. Create `webpack.config.js`

```
module.exports = {
  entry: './node_modules/@kleros/archon/lib/index.js',
  output: {
    filename: 'bundle.js',
    libraryTarget: 'var',
    library: 'Archon'
  }
};
```
This exposes what is exported by library under the variable name Archon

4. `npx webpack`
5.
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Kleros Archon</title>

    <script src="./dist/bundle.js"></script>
    <script>
        var archon = new Archon('https://mainnet.infura.io')
        console.log(archon.version)
    </script>
  </head>
  <body>

  </body>
</html>
```

>> 0.8.0
