### ISSUE TITLE
Use ipfs:// instead of  fs://ipfs

### ISSUE THREAD

**Issue by lidel** [kleros/archon#20]
Hi, this is a drive-by comment from IPFS :car: :dash: 

The `fs:/` was droped as an idea some years ago.
Since then we switched to `ipfs://`, `ipns://` and `dweb:/`
See [ipfs/in-web-browsers/ADDRESSING.md](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md) for up-to-date recommendations.

Would  be fantastic to add archon support for `ipfs://`  and deprecate/remove `fs:/` in code and docs.

**Comment by satello** [comment]
Will do. Thanks for the clarifications in https://github.com/ethereum/EIPs/issues/1497#issuecomment-492997771. For the purposes of this library we will only be dealing with immutable files (at the moment). The preferred URI scheme I have been using is `/ipfs/{cid}`. I had support for `fs:/` and `ipfs:/` to try to cover all standard file formats, I will update to `ipfs://` and `dweb:/` instead

**Comment by jaybuidl** [comment]
Closing this. The current scheme is consistent with Protocol Lab's proposed [Multiaddress](https://github.com/multiformats/multiaddr?tab=readme-ov-file#use-cases) scheme which appears superior to [RFC3986](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Example_URIs) URIs.

Context: https://github.com/kleros/builder-baseline/issues/16
